import { schema } from '@nuxthub/db'
import { pgTable, text, uuid } from 'drizzle-orm/pg-core'

// A table that references another table from NuxtHub's aggregated schema.
//
// Importing `{ schema }` from `@nuxthub/db` is the idiomatic way to reach other tables
// in the aggregated schema — and the ONLY way to reach tables you don't author yourself
// (e.g. the `user` table generated by `@onmax/nuxt-better-auth`). NuxtHub's own docs and
// generated relations use this exact `import { schema } from '@nuxthub/db'` pattern.
//
// The catch: `@nuxthub/db` (the `.` entry) pulls in the `postgres` driver, and NuxtHub
// inlines it into the generated `@nuxthub/db/schema` bundle — silently making the
// "client-safe" schema entry no longer client-safe. See app/app.vue + README.
export const todos = pgTable('todos', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  userId: uuid('user_id').notNull().references(() => schema.users.id),
})
